use crate::config::{
    DisplayFormat, ParameterDef, ParameterKind, ParameterSection, ParameterTab, ParameterValue,
    Visibility,
};
use crate::output::footprint::data::{
    DEFAULT_BAR_MARKER_WIDTH, DEFAULT_BG_MAX_ALPHA, DEFAULT_FONT_SIZE, DEFAULT_MAX_BARS,
};
use data::SerializableColor;

pub(super) fn make_params() -> Vec<ParameterDef> {
    vec![
        // ── General > Typology ──
        ParameterDef {
            key: "data_type".into(),
            label: "Data Type".into(),
            description: "What data to display at each price level".into(),
            kind: ParameterKind::Choice {
                options: &["Volume", "Bid/Ask Split", "Delta", "Delta + Volume"],
            },
            default: ParameterValue::Choice("Volume".to_string()),
            tab: ParameterTab::Parameters,
            section: Some(ParameterSection {
                label: "Render Mode",
                order: 0,
            }),
            order: 0,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "mode".into(),
            label: "Mode".into(),
            description: "Rendering mode: Box (colored grid) or Profile (bars)".into(),
            kind: ParameterKind::Choice {
                options: &["Profile", "Box"],
            },
            default: ParameterValue::Choice("Profile".to_string()),
            tab: ParameterTab::Parameters,
            section: Some(ParameterSection {
                label: "Render Mode",
                order: 0,
            }),
            order: 1,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
        // ── General > Tick Grouping ──
        ParameterDef {
            key: "auto_grouping".into(),
            label: "Grouping".into(),
            description: "Automatic or Manual tick grouping".into(),
            kind: ParameterKind::Choice {
                options: &["Automatic", "Manual"],
            },
            default: ParameterValue::Choice("Automatic".to_string()),
            tab: ParameterTab::Parameters,
            section: Some(ParameterSection {
                label: "Tick Grouping",
                order: 1,
            }),
            order: 0,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "auto_group_factor".into(),
            label: "Auto Group Factor".into(),
            description: "Tick size multiplier for automatic grouping".into(),
            kind: ParameterKind::Integer { min: 1, max: 100 },
            default: ParameterValue::Integer(1),
            tab: ParameterTab::Parameters,
            section: Some(ParameterSection {
                label: "Tick Grouping",
                order: 1,
            }),
            order: 1,
            format: DisplayFormat::Auto,
            visible_when: Visibility::WhenChoice {
                key: "auto_grouping",
                equals: "Automatic",
            },
        },
        ParameterDef {
            key: "manual_ticks".into(),
            label: "Manual Ticks".into(),
            description: "Number of ticks to group together".into(),
            kind: ParameterKind::Integer { min: 1, max: 100 },
            default: ParameterValue::Integer(1),
            tab: ParameterTab::Parameters,
            section: Some(ParameterSection {
                label: "Tick Grouping",
                order: 1,
            }),
            order: 2,
            format: DisplayFormat::Auto,
            visible_when: Visibility::WhenChoice {
                key: "auto_grouping",
                equals: "Manual",
            },
        },
        ParameterDef {
            key: "group_mode".into(),
            label: "Group Mode".into(),
            description: "Bar-based (per candle) or Fixed (uniform) grouping".into(),
            kind: ParameterKind::Choice {
                options: &["Bar-based", "Fixed"],
            },
            default: ParameterValue::Choice("Bar-based".to_string()),
            tab: ParameterTab::Parameters,
            section: Some(ParameterSection {
                label: "Tick Grouping",
                order: 1,
            }),
            order: 3,
            format: DisplayFormat::Auto,
            visible_when: Visibility::WhenChoice {
                key: "auto_grouping",
                equals: "Manual",
            },
        },
        // ── Style > Bar Marker ──
        ParameterDef {
            key: "bar_marker_width".into(),
            label: "Bar Marker Width".into(),
            description: "Width ratio for the candle body marker".into(),
            kind: ParameterKind::Float {
                min: 0.05,
                max: 1.0,
                step: 0.05,
            },
            default: ParameterValue::Float(DEFAULT_BAR_MARKER_WIDTH as f64),
            tab: ParameterTab::Style,
            section: Some(ParameterSection {
                label: "Bar Marker",
                order: 0,
            }),
            order: 0,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "outside_bar_style".into(),
            label: "Outside Bar Style".into(),
            description: "Style for the candle marker outside bars".into(),
            kind: ParameterKind::Choice {
                options: &["Body", "Candle", "None"],
            },
            default: ParameterValue::Choice("Body".to_string()),
            tab: ParameterTab::Style,
            section: Some(ParameterSection {
                label: "Bar Marker",
                order: 0,
            }),
            order: 1,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "marker_alignment".into(),
            label: "Marker Alignment".into(),
            description: "Where the candle body appears relative to bars".into(),
            kind: ParameterKind::Choice {
                options: &["Left", "None", "Center", "Right"],
            },
            default: ParameterValue::Choice("Left".to_string()),
            tab: ParameterTab::Style,
            section: Some(ParameterSection {
                label: "Bar Marker",
                order: 0,
            }),
            order: 2,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "show_outside_border".into(),
            label: "Show Outside Border".into(),
            description: "Draw a border around the candle body marker".into(),
            kind: ParameterKind::Boolean,
            default: ParameterValue::Boolean(false),
            tab: ParameterTab::Display,
            section: None,
            order: 0,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "max_bars_to_show".into(),
            label: "Max Bars".into(),
            description: "Maximum candles to render with footprint levels".into(),
            kind: ParameterKind::Integer { min: 10, max: 1000 },
            default: ParameterValue::Integer(DEFAULT_MAX_BARS as i64),
            tab: ParameterTab::Parameters,
            section: None,
            order: 2,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "scaling".into(),
            label: "Scaling".into(),
            description: "How bar widths are scaled relative to each other".into(),
            kind: ParameterKind::Choice {
                options: &[
                    "Square Root",
                    "Linear",
                    "Logarithmic",
                    "Visible Range",
                    "Datapoint",
                    "Hybrid",
                ],
            },
            default: ParameterValue::Choice("Square Root".to_string()),
            tab: ParameterTab::Style,
            section: Some(ParameterSection {
                label: "Bar Marker",
                order: 0,
            }),
            order: 3,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
        // ── Style > Background ──
        ParameterDef {
            key: "bg_color_mode".into(),
            label: "Background Color".into(),
            description: "Background coloring mode for cells".into(),
            kind: ParameterKind::Choice {
                options: &["Volume Intensity", "Delta Intensity", "None"],
            },
            default: ParameterValue::Choice("Volume Intensity".to_string()),
            tab: ParameterTab::Style,
            section: Some(ParameterSection {
                label: "Background",
                order: 1,
            }),
            order: 0,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "bg_max_alpha".into(),
            label: "Background Max Alpha".into(),
            description: "Maximum opacity for background fills".into(),
            kind: ParameterKind::Float {
                min: 0.0,
                max: 1.0,
                step: 0.05,
            },
            default: ParameterValue::Float(DEFAULT_BG_MAX_ALPHA as f64),
            tab: ParameterTab::Style,
            section: Some(ParameterSection {
                label: "Background",
                order: 1,
            }),
            order: 1,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "bg_buy_color".into(),
            label: "Buy Color".into(),
            description: "Buy/bullish color (defaults to theme)".into(),
            kind: ParameterKind::Color,
            default: ParameterValue::Color(SerializableColor::new(0.0, 0.0, 0.0, 0.0)),
            tab: ParameterTab::Style,
            section: Some(ParameterSection {
                label: "Colors",
                order: 2,
            }),
            order: 0,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "bg_sell_color".into(),
            label: "Sell Color".into(),
            description: "Sell/bearish color (defaults to theme)".into(),
            kind: ParameterKind::Color,
            default: ParameterValue::Color(SerializableColor::new(0.0, 0.0, 0.0, 0.0)),
            tab: ParameterTab::Style,
            section: Some(ParameterSection {
                label: "Colors",
                order: 2,
            }),
            order: 1,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "show_grid_lines".into(),
            label: "Grid Lines".into(),
            description: "Draw cell borders in Box mode".into(),
            kind: ParameterKind::Boolean,
            default: ParameterValue::Boolean(true),
            tab: ParameterTab::Display,
            section: None,
            order: 1,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
        // ── Style > Text ──
        ParameterDef {
            key: "font_size".into(),
            label: "Font Size".into(),
            description: "Text size for level values".into(),
            kind: ParameterKind::Float {
                min: 6.0,
                max: 20.0,
                step: 0.5,
            },
            default: ParameterValue::Float(DEFAULT_FONT_SIZE as f64),
            tab: ParameterTab::Style,
            section: Some(ParameterSection {
                label: "Text",
                order: 3,
            }),
            order: 0,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "text_format".into(),
            label: "Text Format".into(),
            description: "How numeric values are displayed".into(),
            kind: ParameterKind::Choice {
                options: &["Automatic", "Normal", "K"],
            },
            default: ParameterValue::Choice("Automatic".to_string()),
            tab: ParameterTab::Style,
            section: Some(ParameterSection {
                label: "Text",
                order: 3,
            }),
            order: 1,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "dynamic_text_size".into(),
            label: "Dynamic Text Size".into(),
            description: "Automatically adjust text size based on cell size".into(),
            kind: ParameterKind::Boolean,
            default: ParameterValue::Boolean(true),
            tab: ParameterTab::Display,
            section: None,
            order: 2,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "show_zero_values".into(),
            label: "Show Zero Values".into(),
            description: "Display text for levels with zero volume".into(),
            kind: ParameterKind::Boolean,
            default: ParameterValue::Boolean(false),
            tab: ParameterTab::Display,
            section: None,
            order: 3,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "text_color".into(),
            label: "Text Color".into(),
            description: "Color for level value text (defaults to theme)".into(),
            kind: ParameterKind::Color,
            default: ParameterValue::Color(SerializableColor::new(0.0, 0.0, 0.0, 0.0)),
            tab: ParameterTab::Style,
            section: Some(ParameterSection {
                label: "Text",
                order: 3,
            }),
            order: 2,
            format: DisplayFormat::Auto,
            visible_when: Visibility::Always,
        },
    ]
}
