//! IVB study parameter definitions.

use crate::config::{
    DisplayFormat, ParameterDef, ParameterKind, ParameterTab, ParameterValue, Visibility,
};
use data::SerializableColor;

pub fn build_parameter_defs() -> Vec<ParameterDef> {
    vec![
        // ── Parameters tab ────────────────────────────────────
        ParameterDef {
            key: "or_window_minutes".into(),
            label: "OR Window".into(),
            description: "Opening range window in minutes".into(),
            kind: ParameterKind::Choice {
                options: &["5", "15", "30", "60"],
            },
            default: ParameterValue::Choice("30".into()),
            tab: ParameterTab::Parameters,
            section: None,
            order: 0,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "min_samples".into(),
            label: "Min Samples".into(),
            description: "Minimum historical sessions for stats".into(),
            kind: ParameterKind::Integer { min: 5, max: 100 },
            default: ParameterValue::Integer(30),
            tab: ParameterTab::Parameters,
            section: None,
            order: 1,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "recent_window".into(),
            label: "Lookback".into(),
            description: "Number of recent sessions to analyze".into(),
            kind: ParameterKind::Integer { min: 10, max: 500 },
            default: ParameterValue::Integer(50),
            tab: ParameterTab::Parameters,
            section: None,
            order: 2,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "range_narrow_pct".into(),
            label: "Narrow Threshold".into(),
            description: "Percentile below which OR is narrow".into(),
            kind: ParameterKind::Integer { min: 10, max: 40 },
            default: ParameterValue::Integer(25),
            tab: ParameterTab::Parameters,
            section: None,
            order: 3,
            format: DisplayFormat::Percent,
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "range_wide_pct".into(),
            label: "Wide Threshold".into(),
            description: "Percentile above which OR is wide".into(),
            kind: ParameterKind::Integer { min: 60, max: 95 },
            default: ParameterValue::Integer(75),
            tab: ParameterTab::Parameters,
            section: None,
            order: 4,
            format: DisplayFormat::Percent,
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "use_conditional".into(),
            label: "Conditional Filtering".into(),
            description: "Filter by OR range regime for more relevant stats".into(),
            kind: ParameterKind::Boolean,
            default: ParameterValue::Boolean(true),
            tab: ParameterTab::Parameters,
            section: None,
            order: 5,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "gap_threshold_pct".into(),
            label: "Gap Threshold".into(),
            description: "Gap size as % of OR range to \
                classify as Gap Up/Down"
                .into(),
            kind: ParameterKind::Float {
                min: 0.1,
                max: 2.0,
                step: 0.1,
            },
            default: ParameterValue::Float(0.5),
            tab: ParameterTab::Parameters,
            section: None,
            order: 6,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "min_extension".into(),
            label: "Min Extension".into(),
            description: "Minimum extension ratio to include \
                 (filters noise breakouts)"
                .into(),
            kind: ParameterKind::Float {
                min: 0.0,
                max: 0.5,
                step: 0.05,
            },
            default: ParameterValue::Float(0.1),
            tab: ParameterTab::Parameters,
            section: None,
            order: 7,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "decay_rate".into(),
            label: "Recency Decay".into(),
            description: "Exponential decay rate for weighting \
                 recent sessions more (0 = uniform)"
                .into(),
            kind: ParameterKind::Float {
                min: 0.0,
                max: 0.10,
                step: 0.01,
            },
            default: ParameterValue::Float(0.03),
            tab: ParameterTab::Parameters,
            section: None,
            order: 8,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        // ── Display tab ───────────────────────────────────────
        ParameterDef {
            key: "show_or_range".into(),
            label: "Show OR Range".into(),
            description: "Show opening range high/low/mid".into(),
            kind: ParameterKind::Boolean,
            default: ParameterValue::Boolean(true),
            tab: ParameterTab::Display,
            section: None,
            order: 0,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "show_protection".into(),
            label: "Show Protection".into(),
            description: "Show median (protection) levels".into(),
            kind: ParameterKind::Boolean,
            default: ParameterValue::Boolean(true),
            tab: ParameterTab::Display,
            section: None,
            order: 1,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "show_average".into(),
            label: "Show Average".into(),
            description: "Show mean (average) levels".into(),
            kind: ParameterKind::Boolean,
            default: ParameterValue::Boolean(true),
            tab: ParameterTab::Display,
            section: None,
            order: 2,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "show_projection".into(),
            label: "Show Projection".into(),
            description: "Show mean+1σ (projection) levels".into(),
            kind: ParameterKind::Boolean,
            default: ParameterValue::Boolean(true),
            tab: ParameterTab::Display,
            section: None,
            order: 3,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "show_labels".into(),
            label: "Show Labels".into(),
            description: "Show level labels".into(),
            kind: ParameterKind::Boolean,
            default: ParameterValue::Boolean(true),
            tab: ParameterTab::Display,
            section: None,
            order: 4,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "show_stats_in_labels".into(),
            label: "Stats in Labels".into(),
            description: "Include sample count and rates in labels".into(),
            kind: ParameterKind::Boolean,
            default: ParameterValue::Boolean(true),
            tab: ParameterTab::Display,
            section: None,
            order: 5,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "show_downside".into(),
            label: "Show Downside".into(),
            description: "Show downside projection levels".into(),
            kind: ParameterKind::Boolean,
            default: ParameterValue::Boolean(true),
            tab: ParameterTab::Display,
            section: None,
            order: 6,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "max_sessions".into(),
            label: "Max Sessions".into(),
            description: "Number of RTH sessions to display \
                (1 = current only)"
                .into(),
            kind: ParameterKind::Integer { min: 1, max: 10 },
            default: ParameterValue::Integer(1),
            tab: ParameterTab::Display,
            section: None,
            order: 7,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        // ── Style tab ─────────────────────────────────────────
        ParameterDef {
            key: "or_high_color".into(),
            label: "OR High Color".into(),
            description: "Color for OR high level".into(),
            kind: ParameterKind::Color,
            default: ParameterValue::Color(SerializableColor::new(0.2, 0.8, 0.2, 1.0)),
            tab: ParameterTab::Style,
            section: None,
            order: 0,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "or_low_color".into(),
            label: "OR Low Color".into(),
            description: "Color for OR low level".into(),
            kind: ParameterKind::Color,
            default: ParameterValue::Color(SerializableColor::new(0.8, 0.2, 0.2, 1.0)),
            tab: ParameterTab::Style,
            section: None,
            order: 1,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "or_mid_color".into(),
            label: "OR Mid Color".into(),
            description: "Color for OR midpoint".into(),
            kind: ParameterKind::Color,
            default: ParameterValue::Color(SerializableColor::new(0.5, 0.5, 0.5, 1.0)),
            tab: ParameterTab::Style,
            section: None,
            order: 2,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "protection_color".into(),
            label: "Protection Color".into(),
            description: "Color for protection (median) levels".into(),
            kind: ParameterKind::Color,
            default: ParameterValue::Color(SerializableColor::new(0.29, 0.56, 0.85, 1.0)),
            tab: ParameterTab::Style,
            section: None,
            order: 3,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "average_color".into(),
            label: "Average Color".into(),
            description: "Color for average (mean) levels".into(),
            kind: ParameterKind::Color,
            default: ParameterValue::Color(SerializableColor::new(0.83, 0.66, 0.26, 1.0)),
            tab: ParameterTab::Style,
            section: None,
            order: 4,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "projection_color".into(),
            label: "Projection Color".into(),
            description: "Color for projection (mean+1σ) levels".into(),
            kind: ParameterKind::Color,
            default: ParameterValue::Color(SerializableColor::new(0.91, 0.49, 0.24, 1.0)),
            tab: ParameterTab::Style,
            section: None,
            order: 5,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
        ParameterDef {
            key: "level_width".into(),
            label: "Level Width".into(),
            description: "Line width for levels".into(),
            kind: ParameterKind::Float {
                min: 0.5,
                max: 3.0,
                step: 0.5,
            },
            default: ParameterValue::Float(1.0),
            tab: ParameterTab::Style,
            section: None,
            order: 7,
            format: DisplayFormat::default(),
            visible_when: Visibility::Always,
        },
    ]
}
