pub mod analysis;
pub mod config;
pub mod engine;
pub mod feed;
pub mod fill;
pub mod optimization;
pub mod order;
pub mod output;
pub mod portfolio;
pub mod prelude;
pub mod strategy;

pub use config::backtest::BacktestConfig;
pub use config::risk::{PositionSizeMode, RiskConfig, SlippageModel};
pub use engine::runner::BacktestRunner;
pub use feed::provider::TradeProvider;
pub use output::metrics::PerformanceMetrics;
pub use output::progress::BacktestProgressEvent;
pub use output::result::BacktestResult;
pub use output::trade_record::{ExitReason, TradeRecord};
pub use portfolio::equity::{EquityCurve, EquityPoint};
pub use strategy::metadata::{StrategyCategory, StrategyMetadata};
pub use strategy::registry::{StrategyInfo, StrategyRegistry};
pub use strategy::{BacktestError, OrderEvent, Strategy, StrategyContext, StudyBank, StudyRequest};
